# Generated by Django 5.1.5 on 2025-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('smobile', models.CharField(max_length=10)),
            ],
        ),
    ]
